#!/usr/bin/env node
// Generate the AI-agent capability map (llms.txt) and mirror the documentation
// into the npm package so both ship in the tarball.
//
// Agents discover a library from what `npm install` puts on disk — web fetches
// are a forced fallback. So the package root carries:
//   - llms.txt   (this generator's output: contracts, task routing, verified
//                 function cards, advanced recipes, full function index)
//   - docs/      (the hand-written guides + categorized API page, minus
//                 site-only .mdx pages)
//
// Sources of truth (edit these, then re-run):
//   tools/llms/header.md    — identity, runtime matrix, contracts, I/O recipe
//   tools/llms/cards.md     — task routing + verified per-function cards
//   tools/llms/recipes.md   — verified advanced MIR recipes
//   docs/api-by-category.md — the full function index (auto-extracted)
//
// Outputs:
//   llms.txt                        (tracked — repo root, GitHub surface)
//   packages/pleco-xa/llms.txt      (build artifact — ships in the tarball)
//   packages/pleco-xa/docs/         (build artifact — ships in the tarball)
//   apps/docs/public/llms.txt       (build artifact — served at plecoxa.com/llms.txt)
//
// CI regenerates and fails on drift, so the tracked copy can never go stale.
// Zero dependencies — Node built-ins only.

import { readFileSync, writeFileSync, mkdirSync, rmSync, cpSync } from 'node:fs'
import { join, resolve, dirname } from 'node:path'
import { fileURLToPath } from 'node:url'

const repo = resolve(dirname(fileURLToPath(import.meta.url)), '..')
const read = (p) => readFileSync(join(repo, p), 'utf8')

// ---------- assemble llms.txt ----------
const header = read('tools/llms/header.md').trim()
const equivalence = read('tools/llms/equivalence.md').trim()
const cards = read('tools/llms/cards.md').trim()
const recipes = read('tools/llms/recipes.md').trim()

// Full function index, auto-extracted from the categorized API page.
const categoryMd = read('docs/api-by-category.md')
const groups = []
let cur = null
for (const line of categoryMd.split('\n')) {
  const h = line.match(/^## (.+)$/)
  if (h) { cur = { cat: h[1].trim(), fns: [] }; groups.push(cur); continue }
  const row = line.match(/^\| \[`([^`]+)`\]\([^)]*\) \| (.+?) \|/)
  if (row && cur) cur.fns.push({ name: row[1], desc: row[2].trim() })
}
const total = groups.reduce((s, g) => s + g.fns.length, 0)
if (groups.length < 20 || total < 250) {
  throw new Error(`generate-llms: api-by-category parse looks wrong (${groups.length} groups, ${total} functions)`)
}
const index = [
  `## Full function index (${total} exports, by category)`,
  '',
  'One line each — full signatures on the per-function pages at',
  'https://plecoxa.com/api-by-category/ (and in the shipped TypeScript declarations).',
  '',
  ...groups.flatMap((g) => [
    `### ${g.cat}`,
    ...g.fns.map((f) => `- \`${f.name}\` — ${f.desc}`),
    '',
  ]),
].join('\n')

const footer = [
  '## Links',
  '',
  '- Docs, guides, live demo gallery: https://plecoxa.com',
  '- Categorized API reference: https://plecoxa.com/api-by-category/',
  '- This package ships the guides in `docs/` — no fetch needed.',
  '- Repository: https://github.com/pleco-xa/pleco-xa',
  '',
  `Generated by tools/generate-llms.mjs — do not edit outputs by hand.`,
].join('\n')

const out = [header, equivalence, cards, recipes, index, footer].join('\n\n---\n\n') + '\n'

writeFileSync(join(repo, 'llms.txt'), out)
writeFileSync(join(repo, 'packages/pleco-xa/llms.txt'), out)
// Verification ledger ships in the tarball alongside llms.txt (build artifact;
// the tracked source of truth is the repo-root VERIFICATION.md).
writeFileSync(join(repo, 'packages/pleco-xa/VERIFICATION.md'), read('VERIFICATION.md'))
mkdirSync(join(repo, 'apps/docs/public'), { recursive: true })
writeFileSync(join(repo, 'apps/docs/public/llms.txt'), out)

// ---------- machine-readable export manifest (api-manifest.json) ----------
// Tools and agents parse JSON more reliably than markdown. One entry per
// function: category, import form, description, and (where the equivalence
// table maps it) the Python-stack equivalent name.
const equivalents = {}
for (const line of equivalence.split('\n')) {
  const m = line.match(/^\| `((?:librosa)\.[^`]+)`[^|]*\| `([a-zA-Z_$][\w.$]*)/)
  if (m) equivalents[m[2]] = m[1]
}
const manifest = {}
for (const g of groups) {
  for (const f of g.fns) {
    const ns = f.name.includes('.') ? f.name.split('.')[0] : null
    manifest[f.name] = {
      category: g.cat,
      import: ns
        ? `import { ${f.name.split('.')[1]} } from 'pleco-xa/${ns}'`
        : `import { ${f.name} } from 'pleco-xa'`,
      description: f.desc,
      ...(equivalents[f.name] && { equivalent: equivalents[f.name] }),
    }
  }
}
writeFileSync(
  join(repo, 'packages/pleco-xa/api-manifest.json'),
  JSON.stringify(manifest, null, 1) + '\n',
)

// ---------- mirror docs into the package (tarball-shipped documentation) ----------
const pkgDocs = join(repo, 'packages/pleco-xa/docs')
rmSync(pkgDocs, { recursive: true, force: true })
mkdirSync(pkgDocs, { recursive: true })
// Ship the plain-markdown documentation; exclude site-only .mdx pages and the
// gallery (browser-dependent). docs/README.md becomes the index.
cpSync(join(repo, 'docs'), pkgDocs, {
  recursive: true,
  filter: (src) => !src.endsWith('.mdx') && !src.includes('/gallery'),
})

console.log(
  `[generate-llms] llms.txt: ${Math.round(out.length / 1024)} kB ` +
  `(${groups.length} categories, ${total} functions) -> repo root, package, site; ` +
  `docs mirrored into packages/pleco-xa/docs/`,
)
